### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by amarleo130** [itsaky/AndroidIDE#386] opened 2022-08-16 23:45 UTC
### What happened?

when using find in project. 

AndroidIDE crash report
Manufacturer: vivo
Device: vivo1907
App version: 2.1.1-beta (211)

 Stacktrace: 
java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.widget.CheckBox.isChecked()' on a null object reference
	at com.itsaky.androidide.EditorActivity.lambda$createFindInProjectDialog$48$com-itsaky-androidide-EditorActivity(EditorActivity.java:1752)
	at com.itsaky.androidide.EditorActivity$$ExternalSyntheticLambda11.onClick(Unknown Source:6)
	at androidx.appcompat.app.AlertController$ButtonHandler.handleMessage(AlertController.java:167)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:233)
	at android.os.Looper.loop(Looper.java:334)
	at android.app.ActivityThread.main(ActivityThread.java:8396)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:582)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1068)
![Screenshot_20220817_074407](https://user-images.githubusercontent.com/103865951/185003846-e73c11c6-2f10-4765-86ec-dc8220b4fad6.jpg)

### What's the expected behavior?

![Screenshot_20220817_074407](https://user-images.githubusercontent.com/103865951/185003902-bf5eea12-f97c-47b4-a301-70ee44ed59d5.jpg)

### What version of AndroidIDE you're using?

v2.1.1

### Duplicate issues

- [X] This issue has not been reported yet.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by BanDroid** [comment] 2022-08-16 23:53
This is already fixed, wait for next release. Also, dont create duplicate issue, search for issue that is referencing this bug before creating a new one! [#276](https://github.com/itsaky/AndroidIDE/issues/276)

**Comment by itsaky** [comment] 2022-08-18 14:10
Duplicate of #276.

**Closed by itsaky** 2022-08-18 14:10 UTC
Labels: bug
