### ISSUE TITLE
[BUG] DirectoryNotEmpty

### ISSUE THREAD

**Issue by thewolfprod** [itsaky/AndroidIDE#53] opened 2022-01-19 08:35 UTC
**Describe the bug**
It just shows when im trying open terminal.
Im using latest build

**To Reproduce**
1. Click on 'TERMINAL' to open Terminal
2. See error

**Expected behavior**
Terminal opens without errors?

**Details (please complete the following information):**
AndroidIDE crash report
Manufacturer: HUAWEI
Device: SNE-LX1
App version: 2.0-beta (200)

 Stacktrace: 
java.nio.file.DirectoryNotEmptyException: /data/data/com.itsaky.androidide/files/sysroot
	at sun.nio.fs.UnixFileSystemProvider.implDelete(UnixFileSystemProvider.java:242)
	at sun.nio.fs.AbstractFileSystemProvider.delete(AbstractFileSystemProvider.java:103)
	at java.nio.file.Files.delete(Files.java:1126)
	at com.itsaky.androidide.utils.BootstrapInstaller.lambda$doInstall$0(BootstrapInstaller.java:80)
 Caused by: java.util.concurrent.CompletionException: java.nio.file.DirectoryNotEmptyException: /data/data/com.itsaky.androidide/files/sysroot
	at com.itsaky.androidide.utils.BootstrapInstaller.lambda$doInstall$0(BootstrapInstaller.java:83)
	at com.itsaky.androidide.utils.BootstrapInstaller$$ExternalSyntheticLambda0.run(Unknown Source:4)
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1663)
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1655)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:285)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1155)
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1993)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1941)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)

**Comment by itsaky** [comment] 2022-01-19 10:39
Duplicate of #51.

**Closed by itsaky** 2022-01-19 10:39 UTC
Labels: bug

**Comment by thewolfprod** [comment] 2022-01-19 10:54
@itsaky 
But it happens on latest build... it will be fixed
