### ISSUE TITLE
When open my project

### ISSUE THREAD

**Issue by ArjunaKumarMohanta** [itsaky/AndroidIDE#322] opened 2022-07-18 13:45 UTC
AndroidIDE crash report
Manufacturer: Xiaomi
Device: Redmi8
App version: 2.1.1-beta (211)

 Stacktrace: 
com.itsaky.lsp.api.ILanguageServer$AlreadyInitializedException
	at com.itsaky.lsp.java.JavaLanguageServer.initialize(JavaLanguageServer.java:139)
	at com.itsaky.androidide.EditorActivity.initializeLanguageServers(EditorActivity.java:1625)
	at com.itsaky.androidide.EditorActivity.startServices(EditorActivity.java:1605)
	at com.itsaky.androidide.EditorActivity.onCreate(EditorActivity.java:1129)
	at android.app.Activity.performCreate(Activity.java:7906)
	at android.app.Activity.performCreate(Activity.java:7893)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1307)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3283)
 Caused by: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.itsaky.androidide/com.itsaky.androidide.EditorActivity}: com.itsaky.lsp.api.ILanguageServer$AlreadyInitializedException
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3308)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3457)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2044)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:223)
	at android.app.ActivityThread.main(ActivityThread.java:7562)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)

**Comment by itsaky** [comment] 2022-07-18 18:09
Duplicate of #255.

**Closed by itsaky** 2022-07-18 18:09 UTC
Labels: duplicate
