### ISSUE TITLE
Terminal

### ISSUE THREAD

**Issue by Gayour1** [itsaky/AndroidIDE#103] opened 2022-02-09 11:15 UTC
AndroidIDE crash report
Manufacturer: samsung
Device: SM-J260G
App version: 2.0-beta (200)

 Stacktrace: 
java.io.FileNotFoundException: /data/data/com.itsaky.androidide/files/sysroot/bin/less (Permission denied)
	at java.io.FileOutputStream.open0(Native Method)
	at java.io.FileOutputStream.open(FileOutputStream.java:287)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:223)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:171)
	at com.itsaky.androidide.utils.BootstrapInstaller.lambda$doInstall$0(BootstrapInstaller.java:121)
 Caused by: java.lang.RuntimeException: java.io.FileNotFoundException: /data/data/com.itsaky.androidide/files/sysroot/bin/less (Permission denied)
	at com.itsaky.androidide.utils.BootstrapInstaller.lambda$doInstall$0(BootstrapInstaller.java:165)
	at com.itsaky.androidide.utils.BootstrapInstaller$$ExternalSyntheticLambda0.run(Unknown Source:4)
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1661)
 Caused by: java.util.concurrent.CompletionException: java.lang.RuntimeException: java.io.FileNotFoundException: /data/data/com.itsaky.androidide/files/sysroot/bin/less (Permission denied)
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:276)
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:282)
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1664)
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1653)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:285)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1152)
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1990)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1938)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)

**Comment by itsaky** [comment] 2022-02-09 11:20
Duplicate of #59.

**Closed by itsaky** 2022-02-09 11:20 UTC
