### ISSUE TITLE
Crash when performing 'Implement abstract methods' action and no type declaration is found for class

### ISSUE THREAD

**Issue by 3091977221** [itsaky/AndroidIDE#327] opened 2022-07-22 15:26 UTC
```
AndroidIDE crash report
Manufacturer: HUAWEI
Device: FRL-AN00a
App version: 2.1.1-beta (211)

 Stacktrace: 
java.lang.RuntimeException:  is not a java source
	at com.itsaky.lsp.java.compiler.SourceFileObject.<init>(SourceFileObject.java:50)
	at com.itsaky.lsp.java.compiler.SourceFileObject.<init>(SourceFileObject.java:46)
	at com.itsaky.lsp.java.compiler.JavaCompilerService.compile(JavaCompilerService.java:350)
	at com.itsaky.lsp.java.rewrite.ImplementAbstractMethods.rewrite(ImplementAbstractMethods.java:87)
	at com.itsaky.lsp.java.rewrite.Rewrite.asCodeActions(Rewrite.java:53)
	at com.itsaky.lsp.java.actions.diagnostics.ImplementAbstractMethodsAction.postExec(ImplementAbstractMethodsAction.kt:92)
	at com.itsaky.androidide.actions.internal.DefaultActionsRegistry.execInBackground$lambda-4$lambda-3(DefaultActionsRegistry.kt:163)
	at com.itsaky.androidide.actions.internal.DefaultActionsRegistry.$r8$lambda$O84T8keIRpuFKjszomPDRel_Lls(Unknown Source:0)
	at com.itsaky.androidide.actions.internal.DefaultActionsRegistry$$ExternalSyntheticLambda2.run(Unknown Source:8)
	at android.os.Handler.handleCallback(Handler.java:900)
	at android.os.Handler.dispatchMessage(Handler.java:103)
	at android.os.Looper.loop(Looper.java:219)
	at android.app.ActivityThread.main(ActivityThread.java:8668)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1109)
```

<img width="320" src="https://user-images.githubusercontent.com/73690771/180472355-aa6d565e-77bf-43c0-b9d0-401e8e7f2878.jpg"/>

**Comment by MatheusTGamerPro** [comment] 2022-07-22 19:50
What are the steps for the error to happen?

**Comment by itsaky** [comment] 2022-07-23 03:11
Duplicate of #323.

**Closed by itsaky** 2022-07-23 03:11 UTC
Labels: duplicate
