### ISSUE TITLE
Failed to initialize settings generic class cache for settings file

### ISSUE THREAD

**Issue by exo200q** [itsaky/AndroidIDE#194] opened 2022-05-18 03:35 UTC
========== [11:06:35] TASK_BEGIN: assembleDebug ==========
Initialized native services in: ROOT/framework/.gradle/native
Initialized jansi services in: ROOT/framework/.gradle/native
The client will now receive all logging from the daemon (pid: 20502). The daemon log file: ROOT/framework/.gradle/daemon/7.3/daemon-20502.out.log
Starting 6th build in daemon [uptime: 9 mins 45.041 secs, performance: 98%]
Using 8 worker leases.
Watching the file system is configured to be enabled if available
File system watching is inactive
Compiling initialization script 'ROOT/init/data/common/androidide.init.gradle' using BuildScriptTransformer.
Starting Build
Compiling settings file '/storage/emulated/0/AndroidIDEProjects/SavingsPlan/settings.gradle' using SubsetScriptTransformer.
Compiling settings file '/storage/emulated/0/AndroidIDEProjects/SavingsPlan/settings.gradle' using SubsetScriptTransformer.
Compiling settings file '/storage/emulated/0/AndroidIDEProjects/SavingsPlan/settings.gradle' using BuildScriptTransformer.
Compiling settings file '/storage/emulated/0/AndroidIDEProjects/SavingsPlan/settings.gradle' using BuildScriptTransformer.
Compiling settings file '/storage/emulated/0/AndroidIDEProjects/SavingsPlan/settings.gradle' using BuildScriptTransformer.

FAILURE: Build failed with an exception.

* What went wrong:
Could not open settings generic class cache for settings file '/storage/emulated/0/AndroidIDEProjects/SavingsPlan/settings.gradle' (ROOT/framework/.gradle/caches/7.3/scripts/3hv46yg5auac088rgldav7pfr).
> Failed to initialize settings generic class cache for settings file '/storage/emulated/0/AndroidIDEProjects/SavingsPlan/settings.gradle' (ROOT/framework/.gradle/caches/7.3/scripts/3hv46yg5auac088rgldav7pfr)

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 6s
Gradle process exited with exit code 1

**Details (please complete the following information):**
 - Device: Oppo F9
 - OS: Android 11
 - AndroidIDE Version: v2.0.1-beta

**Additional context**
i Tried to fix that bug, so please help me, i was amazed this ide ^_^

**Comment by itsaky** [comment] 2022-05-18 08:00
Duplicate of #16.

**Closed by itsaky** 2022-05-18 08:00 UTC
Labels: bug
