### ISSUE TITLE
starting the application 

### ISSUE THREAD

**Issue by michaelrossel5** [itsaky/AndroidIDE#317] opened 2022-07-17 02:24 UTC
```
AndroidIDE crash report
Manufacturer: Xiaomi
Device: M2010J19SL
App version: 2.1.1-beta (211)

 Stacktrace: 
java.lang.NullPointerException: Attempt to read from field 'com.google.android.material.progressindicator.LinearProgressIndicator com.itsaky.androidide.databinding.ActivityEditorBinding.buildProgressIndicator' on a null object reference
	at com.itsaky.androidide.EditorActivity.lambda$onProjectInitialized$19$com-itsaky-androidide-EditorActivity(EditorActivity.java:934)
	at com.itsaky.androidide.EditorActivity$$ExternalSyntheticLambda16.run(Unknown Source:2)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:236)
	at android.app.ActivityThread.main(ActivityThread.java:8087)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:656)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:967)
```

**Comment by itsaky** [comment] 2022-08-05 17:26
Duplicate of #257.

**Closed by itsaky** 2022-08-05 17:26 UTC
Labels: bug
