### ISSUE TITLE
AndroidIDE crash report

### ISSUE THREAD

**Issue by Wendors** [itsaky/AndroidIDE#55] opened 2022-01-20 14:36 UTC
Manufacturer: OPPO
Device: CPH2021
App version: 2.0-beta (200)

 Stacktrace: 
com.itsaky.androidide.utils.BootstrapInstaller$InstallationException: Unable to delete sysroot directory
 Caused by: java.util.concurrent.CompletionException: com.itsaky.androidide.utils.BootstrapInstaller$InstallationException: Unable to delete sysroot directory
	at com.itsaky.androidide.utils.BootstrapInstaller.lambda$doInstall$0(BootstrapInstaller.java:75)
	at com.itsaky.androidide.utils.BootstrapInstaller$$ExternalSyntheticLambda0.run(Unknown Source:4)
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1663)
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1655)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:285)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1155)
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1993)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1941)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)

**Comment by itsaky** [comment] 2022-01-20 14:38
Duplicate of #51.

**Closed by itsaky** 2022-01-20 14:38 UTC
Labels: bug
