### ISSUE TITLE
[BUG] ConcurrentModificationException while expanding file tree nodes

### ISSUE THREAD

**Issue by ani1nonly** [itsaky/AndroidIDE#52] opened 2022-01-18 04:21 UTC
```Stacktrace: 
java.util.ConcurrentModificationException
	at java.util.ArrayList$Itr.next(ArrayList.java:860)
	at com.unnamed.b.atv.view.AndroidTreeView.expandNode(AndroidTreeView.java:231)
	at com.unnamed.b.atv.view.AndroidTreeView.getView(AndroidTreeView.java:132)
	at com.unnamed.b.atv.view.AndroidTreeView.getView(AndroidTreeView.java:137)
	at com.itsaky.androidide.fragments.FileTreeFragment.lambda$listProjectFiles$2$com-itsaky-androidide-fragments-FileTreeFragment(FileTreeFragment.java:208)
	at com.itsaky.androidide.fragments.FileTreeFragment$$ExternalSyntheticLambda0.complete(Unknown Source:4)
	at com.itsaky.androidide.tasks.TaskExecutor.lambda$executeAsync$0(TaskExecutor.java:52)
	at com.itsaky.androidide.tasks.TaskExecutor$$ExternalSyntheticLambda0.run(Unknown Source:4)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:236)
	at android.app.ActivityThread.main(ActivityThread.java:8061)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:656)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:967)
 ```

**Comment by Wendors** [comment] 2022-01-20 14:55
AndroidIDE crash report
Manufacturer: OPPO
Device: CPH2021
App version: 2.0-beta (200)

 Stacktrace: 
com.itsaky.androidide.utils.BootstrapInstaller$InstallationException: Unable to delete sysroot directory
 Caused by: java.util.concurrent.CompletionException: com.itsaky.androidide.utils.BootstrapInstaller$InstallationException: Unable to delete sysroot directory
	at com.itsaky.androidide.utils.BootstrapInstaller.lambda$doInstall$0(BootstrapInstaller.java:75)
	at com.itsaky.androidide.utils.BootstrapInstaller$$ExternalSyntheticLambda0.run(Unknown Source:4)
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1663)
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1655)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:285)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1155)
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1993)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1941)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)

**Comment by itsaky** [comment] 2022-01-21 12:22
@Wendors The bootstrap packages installation issue is already fixed. See #51.

**Comment by itsaky** [comment] 2022-01-21 12:23
@ani1nonly This issue should have been fixed with the latest commits.

**Closed** 2022-01-27 05:15 UTC
Labels: bug
