### ISSUE TITLE
[It crashed when I try to open XML files]

### ISSUE THREAD

**Issue by devbini00** [itsaky/AndroidIDE#44] opened 2022-01-06 11:22 UTC
AndroidIDE crash report
Manufacturer: samsung
Device: SM-A115F
App version: 2.0-beta (200)

 Stacktrace: 
java.lang.NullPointerException: Attempt to invoke virtual method 'void io.github.rosemoe.editor.widget.CodeEditor.close()' on a null object reference
	at com.itsaky.androidide.adapters.EditorPagerAdapter.closeFileAt(EditorPagerAdapter.java:132)
	at com.itsaky.androidide.adapters.EditorPagerAdapter.closeAllFiles(EditorPagerAdapter.java:147)
	at com.itsaky.androidide.EditorActivity.closeAll(EditorActivity.java:903)
	at com.itsaky.androidide.EditorActivity.closeProject(EditorActivity.java:1075)
	at com.itsaky.androidide.EditorActivity.lambda$confirmProjectClose$15$com-itsaky-androidide-EditorActivity(EditorActivity.java:1095)
	at com.itsaky.androidide.EditorActivity$$ExternalSyntheticLambda0.onClick(Unknown Source:2)
	at androidx.appcompat.app.AlertController$ButtonHandler.handleMessage(AlertController.java:167)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:246)
	at android.app.ActivityThread.main(ActivityThread.java:8512)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)

**Screenshots**

**Details (please complete the following information):**
 - Device: [e.g. realme 3 Pro]
 - OS: [e.g. Android 11]
 - AndroidIDE Version [e.g. v1.0.3-alpha]

**Additional context**

**Comment by itsaky** [comment] 2022-01-06 11:24
Duplicate of #43.

**Closed by itsaky** 2022-01-06 11:24 UTC
Labels: bug
