### ISSUE TITLE
AndroidIDE (apk-debug)

### ISSUE THREAD

**Issue by assis-tant** [itsaky/AndroidIDE#249] opened 2022-06-30 02:17 UTC
AndroidIDE crash report
Manufacturer: Xiaomi
Device: M2004J19C
OS version: Miui 12.5
Android version: 11
App version: 2.1.2-beta (212)

AndroidIDE (apk-debug) crashed when opening Terminal. #234 Terminal not opening

 Stacktrace: 
java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object java.util.HashMap.put(java.lang.Object, java.lang.Object)' on a null object reference
	at com.itsaky.androidide.views.virtualkeys.SpecialButton.<init>(SpecialButton.java:27)
	at com.itsaky.androidide.views.virtualkeys.SpecialButton.<clinit>(SpecialButton.java:10)
 Caused by: java.lang.ExceptionInInitializerError
	at com.itsaky.androidide.views.virtualkeys.VirtualKeysView$1.<init>(VirtualKeysView.java:197)
	at com.itsaky.androidide.views.virtualkeys.VirtualKeysView.getDefaultSpecialButtons(VirtualKeysView.java:195)
	at com.itsaky.androidide.views.virtualkeys.VirtualKeysView.<init>(VirtualKeysView.java:162)
 Caused by: java.lang.reflect.InvocationTargetException
 Caused by: android.view.InflateException: Binary XML file line #9 in com.itsaky.androidide:layout/activity_terminal: Error inflating class com.itsaky.androidide.views.virtualkeys.VirtualKeysView
 Caused by: android.view.InflateException: Binary XML file line #9 in com.itsaky.androidide:layout/activity_terminal: Binary XML file line #9 in com.itsaky.androidide:layout/activity_terminal: Error inflating class com.itsaky.androidide.views.virtualkeys.VirtualKeysView
	at java.lang.reflect.Constructor.newInstance0(Native Method)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
	at android.view.LayoutInflater.createView(LayoutInflater.java:856)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:1012)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:963)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:1142)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1103)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:684)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:536)
	at com.itsaky.androidide.databinding.ActivityTerminalBinding.inflate(ActivityTerminalBinding.java:49)
	at com.itsaky.androidide.databinding.ActivityTerminalBinding.inflate(ActivityTerminalBinding.java:43)
	at com.itsaky.androidide.TerminalActivity.bindLayout(TerminalActivity.java:320)
	at com.itsaky.androidide.app.StudioActivity.onCreate(StudioActivity.java:83)
	at com.itsaky.androidide.TerminalActivity.onCreate(TerminalActivity.java:267)
	at android.app.Activity.performCreate(Activity.java:8093)
	at android.app.Activity.performCreate(Activity.java:8067)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1309)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3493)
 Caused by: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.itsaky.androidide/com.itsaky.androidide.TerminalActivity}: android.view.InflateException: Binary XML file line #9 in com.itsaky.androidide:layout/activity_terminal: Binary XML file line #9 in com.itsaky.androidide:layout/activity_terminal: Error inflating class com.itsaky.androidide.views.virtualkeys.VirtualKeysView
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3520)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3692)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2142)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:236)
	at android.app.ActivityThread.main(ActivityThread.java:7864)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:620)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1011)

**Comment by itsaky** [comment] 2022-06-30 02:54
Duplicate of #234.

**Closed by itsaky** 2022-06-30 02:54 UTC
