### ISSUE TITLE
[Bug]: i am just trying to clean and run project.

### ISSUE THREAD

**Issue by Egor1304** [itsaky/AndroidIDE#384] opened 2022-08-16 08:52 UTC
### What happened?

AndroidIDE crash report
Manufacturer: samsung
Device: SM-A125U
App version: 2.1.1-beta (211)

 Stacktrace: 
java.lang.NullPointerException
	at java.util.Objects.requireNonNull(Objects.java:220)
	at com.itsaky.androidide.EditorActivity.initializeLanguageServers(EditorActivity.java:1618)
	at com.itsaky.androidide.EditorActivity.startServices(EditorActivity.java:1605)
	at com.itsaky.androidide.EditorActivity.onCreate(EditorActivity.java:1129)
	at android.app.Activity.performCreate(Activity.java:8207)
	at android.app.Activity.performCreate(Activity.java:8191)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1309)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3819)
 Caused by: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.itsaky.androidide/com.itsaky.androidide.EditorActivity}: java.lang.NullPointerException
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3846)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4022)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2336)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:246)
	at android.app.ActivityThread.main(ActivityThread.java:8653)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)

### What's the expected behavior?

 Idk

### What version of AndroidIDE you're using?

v2.1.1

### Duplicate issues

- [ ] This issue has not been reported yet.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by itsaky** [comment] 2022-08-16 09:32
Duplicate of #235.

Why did you even check the `This issue has not been reported yet.` checkbox? And put the logs in `Relevant log output` field.

**Closed by itsaky** 2022-08-16 09:32 UTC
Labels: bug
