### ISSUE TITLE
Build Release Error Not Found Resource PNG

### ISSUE THREAD

**Issue by masfha** [itsaky/AndroidIDE#377] opened 2022-08-14 20:17 UTC
### What happened?

![Screenshot_2022-08-15-03-09-00-128_com itsaky androidide](https://user-images.githubusercontent.com/79098759/184553305-e49b4553-1a59-4b48-8fb9-d716bcaa5400.jpg)

when the build release the PNG file is not found , even though in the source code the file already exists .

### What's the expected behavior?

Please fix

### What version of AndroidIDE you're using?

v2.1.2 (debug builds)

### Relevant log output

```shell
Executing tasks: assembleRelease

> Configure project :app
WARNING:The option setting 'android.aapt2FromMavenOverride=/data/data/com.itsaky.androidide/files/home/.androidide/aapt2' is experimental.
=====BlackObfuscator=====
BlackObfuscatorExtension{enabled=true, depth=2, obfClass=[com.v2ray.custom], blackClass=[com.v2ray.custom.util.SpeedtestUtil, com.v2ray.custom.ui.ServerCustomConfigActivity]}
=========================
add Task mergeLibDexDebug
add Task mergeProjectDexDebug
Debug mappingFile null
add Task mergeDexRelease
Release mappingFile null

> Task :app:buildKotlinToolingMetadata UP-TO-DATE
> Task :app:preBuild UP-TO-DATE
> Task :app:preReleaseBuild UP-TO-DATE
> Task :app:compileReleaseAidl NO-SOURCE
> Task :app:compileReleaseRenderscript NO-SOURCE
> Task :app:dataBindingMergeDependencyArtifactsRelease
> Task :app:generateReleaseResValues UP-TO-DATE
> Task :app:generateReleaseResources UP-TO-DATE
> Task :app:dataBindingMergeGenClassesRelease
> Task :app:dataBindingTriggerRelease
> Task :app:generateReleaseBuildConfig UP-TO-DATE
> Task :app:checkReleaseAarMetadata
> Task :app:createReleaseCompatibleScreenManifests
> Task :app:extractDeepLinksRelease UP-TO-DATE
> Task :app:mergeReleaseResources FAILED
> Task :app:processReleaseMainManifest

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:mergeReleaseResources'.
> Multiple task action failures occurred:
   > A failure occurred while executing com.android.build.gradle.internal.res.Aapt2CompileRunnable
      > Android resource compilation failed
        ERROR:AAPT: com.v2ray.custom.app-main-48:/drawable-xxhdpi/donate.png: error: file not found.
        
            
   > A failure occurred while executing com.android.build.gradle.internal.res.Aapt2CompileRunnable
      > Android resource compilation failed
        ERROR:AAPT: com.v2ray.custom.app-main-48:/drawable-xhdpi/ic_stat_direct.png: error: file not found.
        
            
   > A failure occurred while executing com.android.build.gradle.internal.res.Aapt2CompileRunnable
      > Android resource compilation failed
        ERROR:AAPT: com.v2ray.custom.app-main-48:/drawable-mdpi/ic_stat_name.png: error: file not found.
        
            
   > A failure occurred while executing com.android.build.gradle.internal.res.Aapt2CompileRunnable
      > Android resource compilation failed
        ERROR:AAPT: com.v2ray.custom.app-main-48:/drawable-xxxhdpi/ic_stat_proxy.png: error: file not found.
        
            
   > A failure occurred while executing com.android.build.gradle.internal.res.Aapt2CompileRunnable
      > Android resource compilation failed
        ERROR:AAPT: com.v2ray.custom.app-main-48:/drawable-hdpi/ic_stat_direct.png: error: file not found.
        
            
   > A failure occurred while executing com.android.build.gradle.internal.res.Aapt2CompileRunnable
      > Android resource compilation failed
        ERROR:AAPT: com.v2ray.custom.app-main-48:/drawable-xxxhdpi/ic_stat_name.png: error: file not found.
        
            
   > A failure occurred while executing com.android.build.gradle.internal.res.Aapt2CompileRunnable
      > Android resource compilation failed
        ERROR:AAPT: com.v2ray.custom.app-main-48:/drawable-xxhdpi/ic_stat_direct.png: error: file not found.
        
            

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 25s
11 actionable tasks: 7 executed, 4 up-to-date
```

### Duplicate issues

- [ ] This issue has not been reported yet.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by itsaky** [comment] 2022-08-15 02:12
Duplicate of #193.

At least search for the issue before opening a new issue. You even checked the `This issue has not been reported yet.`checkbox.

**Closed by itsaky** 2022-08-15 02:12 UTC
Labels: bug
