### ISSUE TITLE
ArrayIndexOutOfBoundsException in GraphicTextRow

### ISSUE THREAD

**Issue by masfha** [itsaky/AndroidIDE#266] opened 2022-07-06 21:50 UTC
![Screenshot_2022-07-07-04-44-25-226_com itsaky androidide](https://user-images.githubusercontent.com/79098759/177649692-3114bc84-4bf6-4fae-af1c-243b593a6f32.jpg)
AndroidIDE crash report
Manufacturer: Xiaomi
Device: M2103K19PG
App version: 2.1.2-beta (212)

 Stacktrace: 
java.lang.ArrayIndexOutOfBoundsException: length=128; index=-1
	at io.github.rosemoe.sora.graphics.GraphicTextRow.measureText(GraphicTextRow.java:252)
	at io.github.rosemoe.sora.widget.layout.LineBreakLayout.getCharLayoutOffset(LineBreakLayout.java:178)
	at io.github.rosemoe.sora.widget.CursorBlink.run(CursorBlink.java:81)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:210)
	at android.os.Looper.loop(Looper.java:299)
	at android.app.ActivityThread.main(ActivityThread.java:8298)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:576)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1073)

**Comment by itsaky** [comment] 2022-07-13 13:42
Duplicate of #195.

**Closed by itsaky** 2022-07-13 13:42 UTC
Labels: bug
