### ISSUE TITLE
[Bug]: Bug when exiting the app and entering again

### ISSUE THREAD

**Issue by PgmDz** [itsaky/AndroidIDE#421] opened 2022-09-02 11:37 UTC
### What happened?

Manufacturer: motorola
Device: motoe6s
App version: 2.1.1-beta (211)

Almost always when I exit AndroidIDE and open another app and then go back to Android IDE it crashes.

And to open again it is necessary to clear cache and force stop.

Maybe it's a problem of high consumption of raw memory.

### What version of AndroidIDE you're using?

v2.1.1

### Relevant log output

```shell
java.lang.NullPointerException
	at java.util.Objects.requireNonNull(Objects.java:203)
	at com.itsaky.androidide.EditorActivity.initializeLanguageServers(EditorActivity.java:1618)
	at com.itsaky.androidide.EditorActivity.startServices(EditorActivity.java:1605)
	at com.itsaky.androidide.EditorActivity.onCreate(EditorActivity.java:1129)
	at android.app.Activity.performCreate(Activity.java:7136)
	at android.app.Activity.performCreate(Activity.java:7127)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1271)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2924)
 Caused by: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.itsaky.androidide/com.itsaky.androidide.EditorActivity}: java.lang.NullPointerException
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2944)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3079)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1836)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:6704)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:916)
```

### Duplicate issues

- [X] This issue has not been reported yet.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by itsaky** [comment] 2022-09-02 12:01
Duplicate of #235.

**Closed by itsaky** 2022-09-02 12:01 UTC
Labels: bug
