### ISSUE TITLE
error

### ISSUE THREAD

**Issue by mobutcher** [itsaky/AndroidIDE#349] opened 2022-08-06 03:43 UTC
AndroidIDE crash report
Manufacturer: HUAWEI
Device: HRY-AL00a
App version: 2.1.1-beta (211)

 Stacktrace: 
com.itsaky.lsp.api.ILanguageServer$AlreadyInitializedException
	at com.itsaky.lsp.java.JavaLanguageServer.initialize(JavaLanguageServer.java:139)
	at com.itsaky.androidide.EditorActivity.initializeLanguageServers(EditorActivity.java:1625)
	at com.itsaky.androidide.EditorActivity.startServices(EditorActivity.java:1605)
	at com.itsaky.androidide.EditorActivity.onCreate(EditorActivity.java:1129)
	at android.app.Activity.performCreate(Activity.java:8214)
	at android.app.Activity.performCreate(Activity.java:8202)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1320)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:4033)
 Caused by: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.itsaky.androidide/com.itsaky.androidide.EditorActivity}: com.itsaky.lsp.api.ILanguageServer$AlreadyInitializedException
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:4060)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4247)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:91)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:149)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:103)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2613)
	at android.os.Handler.dispatchMessage(Handler.java:110)
	at android.os.Looper.loop(Looper.java:219)
	at android.app.ActivityThread.main(ActivityThread.java:8668)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1109)

**Comment by itsaky** [comment] 2022-08-06 12:39
This is a duplicate of #255. At least search for similar issues before opening a new issue.

**Closed by itsaky** 2022-08-06 12:39 UTC
