### ISSUE TITLE
Crash 

### ISSUE THREAD

**Issue by Suryabahadurgauli** [itsaky/AndroidIDE#270] opened 2022-07-09 04:09 UTC
AndroidIDE crash report
Manufacturer: samsung
Device: SM-A260G
App version: 2.1.1-beta (211)

 Stacktrace: 
com.itsaky.lsp.api.ILanguageServer$AlreadyInitializedException
	at com.itsaky.lsp.java.JavaLanguageServer.initialize(JavaLanguageServer.java:139)
	at com.itsaky.androidide.EditorActivity.initializeLanguageServers(EditorActivity.java:1625)
	at com.itsaky.androidide.EditorActivity.startServices(EditorActivity.java:1605)
	at com.itsaky.androidide.EditorActivity.onCreate(EditorActivity.java:1129)
	at android.app.Activity.performCreate(Activity.java:7009)
	at android.app.Activity.performCreate(Activity.java:7000)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1214)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2742)
 Caused by: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.itsaky.androidide/com.itsaky.androidide.EditorActivity}: com.itsaky.lsp.api.ILanguageServer$AlreadyInitializedException
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2789)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2872)
	at android.app.ActivityThread.-wrap11(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1595)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6543)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:440)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:810)

**Comment by itsaky** [comment] 2022-07-09 04:29
Duplicate of #255.

**Closed** 2022-07-10 11:07 UTC
