### ISSUE TITLE
app crashed

### ISSUE THREAD

**Issue by yxom-alt** [itsaky/AndroidIDE#358] opened 2022-08-10 07:15 UTC
```
AndroidIDE crash report
Manufacturer: Meizu
Device: MX4
App version: 2.1.1-beta (211)

 Stacktrace: 
com.itsaky.lsp.api.ILanguageServer$AlreadyInitializedException
	at com.itsaky.lsp.java.JavaLanguageServer.initialize(JavaLanguageServer.java:139)
	at com.itsaky.androidide.EditorActivity.initializeLanguageServers(EditorActivity.java:1625)
	at com.itsaky.androidide.EditorActivity.startServices(EditorActivity.java:1605)
	at com.itsaky.androidide.EditorActivity.onCreate(EditorActivity.java:1129)
	at android.app.Activity.performCreate(Activity.java:7232)
	at android.app.Activity.performCreate(Activity.java:7221)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1272)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2964)
 Caused by: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.itsaky.androidide/com.itsaky.androidide.EditorActivity}: com.itsaky.lsp.api.ILanguageServer$AlreadyInitializedException
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2984)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3119)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1839)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:201)
	at android.app.ActivityThread.main(ActivityThread.java:6861)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)
```

**Comment by itsaky** [comment] 2022-08-10 07:19
Look for similar issues before opening a new issue to avoid duplicates. This is a duplicate of #255.

**Closed by itsaky** 2022-08-10 07:19 UTC
