### ISSUE TITLE
[BUG] Android12 - Tagged pointers & OpenJDK

### ISSUE THREAD

**Issue by vip458** [itsaky/AndroidIDE#133] opened 2022-03-20 11:15 UTC
There are still problems with the new version. Is there a solution to creating an app project and directly reporting an error
<br/><img src="https://user-images.githubusercontent.com/59636798/159159596-7523cbf2-b40c-46d8-a6d7-c9b16d9fbf61.jpg" width="300px"/>

**Comment by itsaky** [comment] 2022-03-20 11:49
This is because of a restriction on 64-bit Android 12 devices.

As this issue occurs only on 64-bit devices, you could try to use APK from [`32-bit-on-Android-12`](https://github.com/itsaky/AndroidIDE/tree/32-bit-on-Android-12) branch. You'll have to install 32-bit build tools on your device (available on [website](https://androidide.com)).

**Comment by ask9027** [comment] 2022-03-24 10:23
> This is because of a restriction on 64-bit Android 12 devices.
> 
> As this issue occurs only on 64-bit devices, you could try to use APK from [`32-bit-on-Android-12`](https://github.com/itsaky/AndroidIDE/tree/32-bit-on-Android-12) branch. You'll have to install 32-bit build tools on your device (available on [website](https://androidide.com)).

Also getting error while using 32bit files.

**Comment by itsaky** [comment] 2022-03-24 15:21
What's the error? Is it the same?

Note that you have to reinstall AndroidIDE (uninstall the current one, then install the [APK from the other branch](https://github.com/itsaky/AndroidIDE/actions/runs/1998850688)). Use 32-bit build tools while installing this APK.

**Comment by ask9027** [comment] 2022-03-24 15:22
Eixt code 1

**Comment by ask9027** [comment] 2022-03-24 15:29
> What's the error? Is it the same?
> 
> Note that you have to reinstall AndroidIDE (uninstall the current one, then install the [APK from the other branch](https://github.com/itsaky/AndroidIDE/actions/runs/1998850688)). Use 32-bit build tools while installing this APK.

downloading 32bit apk now. Let see does it work or not

**Comment by itsaky** [comment] 2022-03-24 15:29
> Note that you have to reinstall AndroidIDE (uninstall the current one, then install the [APK from the other branch](https://github.com/itsaky/AndroidIDE/actions/runs/1998850688)). Use 32-bit build tools while installing this APK.

Read this carefully.

**Comment by ask9027** [comment] 2022-03-24 15:40
`========== [21:09:50] TASK_BEGIN: assembleDebug ==========
Initialized native services in: ROOT/framework/.gradle/native
Initialized jansi services in: ROOT/framework/.gradle/native
Removing 0 daemon stop events from registry
Starting a Gradle Daemon (subsequent builds will be faster)
Starting process 'Gradle build daemon'. Working directory: ROOT/framework/.gradle/daemon/7.3 Command: ROOT/framework/jdk/bin/java --add-opens java.base/java.util=ALL-UNNAMED --add-opens java.base/java.lang=ALL-UNNAMED --add-opens java.base/java.lang.invoke=ALL-UNNAMED --add-opens java.base/java.util=ALL-UNNAMED --add-opens java.prefs/java.util.prefs=ALL-UNNAMED --add-opens java.prefs/java.util.prefs=ALL-UNNAMED --add-opens java.base/java.nio.charset=ALL-UNNAMED --add-opens java.base/java.net=ALL-UNNAMED --add-opens java.base/java.util.concurrent.atomic=ALL-UNNAMED -Xmx2048m -Dfile.encoding=UTF-8 -Duser.country -Duser.language=en -Duser.variant -cp ROOT/framework/.gradle/wrapper/dists/gradle-7.3-bin/ddwl0k7mt9g6ak16i1m905vyv/gradle-7.3/lib/gradle-launcher-7.3.jar org.gradle.launcher.daemon.bootstrap.GradleDaemon 7.3
Successfully started process 'Gradle build daemon'
Could not write standard input to Gradle build daemon.
java.io.IOException: Stream closed
at java.base/java.lang.ProcessBuilder$NullOutputStream.write(ProcessBuilder.java:442)
at java.base/java.io.OutputStream.write(OutputStream.java:157)
at java.base/java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:81)
at java.base/java.io.BufferedOutputStream.flush(BufferedOutputStream.java:142)
at org.gradle.process.internal.streams.ExecOutputHandleRunner.forwardContent(ExecOutputHandleRunner.java:68)
at org.gradle.process.internal.streams.ExecOutputHandleRunner.run(ExecOutputHandleRunner.java:53)
at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:61)
at java.base/java.lang.Thread.run(Thread.java:829)
An attempt to start the daemon took 0.199 secs.

FAILURE: Build failed with an exception.

* What went wrong:
Unable to start the daemon process.
This problem might be caused by incorrect configuration of the daemon.
For example, an unrecognized jvm option is used.
Please refer to the User Manual chapter on the daemon at https://docs.gradle.org/7.3/userguide/gradle_daemon.html
Process command line: ROOT/framework/jdk/bin/java --add-opens java.base/java.util=ALL-UNNAMED --add-opens java.base/java.lang=ALL-UNNAMED --add-opens java.base/java.lang.invoke=ALL-UNNAMED --add-opens java.base/java.util=ALL-UNNAMED --add-opens java.prefs/java.util.prefs=ALL-UNNAMED --add-opens java.prefs/java.util.prefs=ALL-UNNAMED --add-opens java.base/java.nio.charset=ALL-UNNAMED --add-opens java.base/java.net=ALL-UNNAMED --add-opens java.base/java.util.concurrent.atomic=ALL-UNNAMED -Xmx2048m -Dfile.encoding=UTF-8 -Duser.country -Duser.language=en -Duser.variant -cp ROOT/framework/.gradle/wrapper/dists/gradle-7.3-bin/ddwl0k7mt9g6ak16i1m905vyv/gradle-7.3/lib/gradle-launcher-7.3.jar org.gradle.launcher.daemon.bootstrap.GradleDaemon 7.3
Please read the following process output to find out more:
-----------------------
Error occurred during initialization of VM
Could not reserve enough space for 2097152KB object heap


* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org
Gradle process exited with exit code 1
`

**Comment by ask9027** [comment] 2022-03-24 15:43
> `========== [21:09:50] TASK_BEGIN: assembleDebug ========== Initialized native services in: ROOT/framework/.gradle/native Initialized jansi services in: ROOT/framework/.gradle/native Removing 0 daemon stop events from registry Starting a Gradle Daemon (subsequent builds will be faster) Starting process 'Gradle build daemon'. Working directory: ROOT/framework/.gradle/daemon/7.3 Command: ROOT/framework/jdk/bin/java --add-opens java.base/java.util=ALL-UNNAMED --add-opens java.base/java.lang=ALL-UNNAMED --add-opens java.base/java.lang.invoke=ALL-UNNAMED --add-opens java.base/java.util=ALL-UNNAMED --add-opens java.prefs/java.util.prefs=ALL-UNNAMED --add-opens java.prefs/java.util.prefs=ALL-UNNAMED --add-opens java.base/java.nio.charset=ALL-UNNAMED --add-opens java.base/java.net=ALL-UNNAMED --add-opens java.base/java.util.concurrent.atomic=ALL-UNNAMED -Xmx2048m -Dfile.encoding=UTF-8 -Duser.country -Duser.language=en -Duser.variant -cp ROOT/framework/.gradle/wrapper/dists/gradle-7.3-bin/ddwl0k7mt9g6ak16i1m905vyv/gradle-7.3/lib/gradle-launcher-7.3.jar org.gradle.launcher.daemon.bootstrap.GradleDaemon 7.3 Successfully started process 'Gradle build daemon' Could not write standard input to Gradle build daemon. java.io.IOException: Stream closed at java.base/java.lang.ProcessBuilder$NullOutputStream.write(ProcessBuilder.java:442) at java.base/java.io.OutputStream.write(OutputStream.java:157) at java.base/java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:81) at java.base/java.io.BufferedOutputStream.flush(BufferedOutputStream.java:142) at org.gradle.process.internal.streams.ExecOutputHandleRunner.forwardContent(ExecOutputHandleRunner.java:68) at org.gradle.process.internal.streams.ExecOutputHandleRunner.run(ExecOutputHandleRunner.java:53) at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64) at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48) at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:61) at java.base/java.lang.Thread.run(Thread.java:829) An attempt to start the daemon took 0.199 secs.
> 
> FAILURE: Build failed with an exception.
> 
> * What went wrong:
>   Unable to start the daemon process.
>   This problem might be caused by incorrect configuration of the daemon.
>   For example, an unrecognized jvm option is used.
>   Please refer to the User Manual chapter on the daemon at https://docs.gradle.org/7.3/userguide/gradle_daemon.html
>   Process command line: ROOT/framework/jdk/bin/java --add-opens java.base/java.util=ALL-UNNAMED --add-opens java.base/java.lang=ALL-UNNAMED --add-opens java.base/java.lang.invoke=ALL-UNNAMED --add-opens java.base/java.util=ALL-UNNAMED --add-opens java.prefs/java.util.prefs=ALL-UNNAMED --add-opens java.prefs/java.util.prefs=ALL-UNNAMED --add-opens java.base/java.nio.charset=ALL-UNNAMED --add-opens java.base/java.net=ALL-UNNAMED --add-opens java.base/java.util.concurrent.atomic=ALL-UNNAMED -Xmx2048m -Dfile.encoding=UTF-8 -Duser.country -Duser.language=en -Duser.variant -cp ROOT/framework/.gradle/wrapper/dists/gradle-7.3-bin/ddwl0k7mt9g6ak16i1m905vyv/gradle-7.3/lib/gradle-launcher-7.3.jar org.gradle.launcher.daemon.bootstrap.GradleDaemon 7.3
>   Please read the following process output to find out more:
> 
> Error occurred during initialization of VM Could not reserve enough space for 2097152KB object heap
> 
> * Try:
> 
> > Run with --stacktrace option to get the stack trace.
> > Run with --debug option to get more log output.
> > Run with --scan to get full insights.
> 
> * Get more help at https://help.gradle.org
>   Gradle process exited with exit code 1
>   `

After using APK from other source with 32bit build files.

**Comment by itsaky** [comment] 2022-03-24 15:49
Reduce the Xmx in gradle.properties to 1024m.

Also, read the contributing guide. Specifically the part where it says that you have put build outputs, stacktraces, etc in `code blocks`.

**Comment by ask9027** [comment] 2022-03-24 15:51
> Reduce the Xmx in gradle.properties to 1024m.
> 
> Also, read the contributing guide. Specifically the part where it says that you have put build outputs, stacktraces, etc in `code blocks`.

Okay, but what is the solution for it?

**Comment by itsaky** [comment] 2022-03-24 15:54
[Read this](https://stackoverflow.com/a/14763095).

**Comment by ask9027** [comment] 2022-03-24 15:59
> [Read this](https://stackoverflow.com/a/14763095).

Got it.. 👍

**Comment by ask9027** [comment] 2022-03-26 09:46
Successfully build an apk in Android Studio in proot-distro ubuntu using ANDROIDIDE 32bit buildtools (android-sdk, jdk-11,aapt2).
![Screenshot_2022-03-26-14-47-55-801_com realvnc viewer android](https://user-images.githubusercontent.com/61283438/160234046-d3375f2c-7f00-4fb6-9bac-68a51314f2d7.jpg)
![Screenshot_2022-03-26-14-52-01-790_com realvnc viewer android](https://user-images.githubusercontent.com/61283438/160234051-7c08e228-122c-44c8-8a49-3d2e33e56855.jpg)
![Screenshot_2022-03-26-14-52-13-973_com realvnc viewer android](https://user-images.githubusercontent.com/61283438/160234055-c86c4fcb-4cad-4cdd-958a-cb4df7ac8c03.jpg)
![Screenshot_2022-03-26-14-52-28-462_com realvnc viewer android](https://user-images.githubusercontent.com/61283438/160234056-9ff6784b-1c1b-4989-9a2d-0f8bacabcb77.jpg)

https://user-images.githubusercontent.com/61283438/160234059-5f664131-5f25-4b05-bbb6-98063dbcd51e.mp4

**Comment by itsaky** [comment] 2022-03-26 10:30
And how is it related to this issue?

**Comment by Etanarvazac** [comment] 2022-04-10 20:47
In regards to Issue #28, I finally managed to get a build near complete. The error I got stated NDK was invalid. This error cleared 5 minutes later and now I am stuck on this error:
![SmartSelect_20220410-163430_AndroidIDE.jpg](https://user-images.githubusercontent.com/55290878/162639004-d7606db2-48ed-4775-a4d3-e8fe7fd36495.jpg)
Which is the change noted to me via the terminal. First run worked with change, second threw above error. I can create a separate ticket if you'd like, but this solution was originally a Android 12 heap pointer error resolution.

**Comment by itsaky** [comment] 2022-06-10 17:19
This has been fixed in the latest commits. Please see [this](https://t.me/androidide_discussions/30564) for more info.

**Closed by itsaky** 2022-06-10 17:19 UTC
Labels: bug

**Comment by moeado** [comment] 2022-06-13 10:02
Solved but is there any way to run the 64 version?

**Comment by moeado** [comment] 2022-06-13 13:48
I followed the link and got this error 

======= [15:31:55] TASK_BEGIN: assembleDebug ==========
CANNOT LINK EXECUTABLE "ROOT/framework/jdk/bin/java": "ROOT/sysroot/lib/libz.so.1.2.11" is 32-bit instead of 64-bit
Gradle process exited with exit code 1
