### ISSUE TITLE
Can't open the project

### ISSUE THREAD

**Issue by zaynwinchester** [itsaky/AndroidIDE#252] opened 2022-07-01 06:16 UTC
AndroidIDE crash report
Manufacturer: vivo
Device: V2134
App version: 2.1.2-beta (212)

 Stacktrace: 
java.lang.NullPointerException
	at java.util.Objects.requireNonNull(Objects.java:220)
	at com.itsaky.androidide.app.StudioApp.getJavaLanguageServer(StudioApp.java:109)
	at com.itsaky.androidide.EditorActivity.initializeLanguageServers(EditorActivity.java:1627)
	at com.itsaky.androidide.EditorActivity.startServices(EditorActivity.java:1617)
	at com.itsaky.androidide.EditorActivity.onCreate(EditorActivity.java:1163)
	at android.app.Activity.performCreate(Activity.java:8359)
	at android.app.Activity.performCreate(Activity.java:8337)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1329)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3894)
 Caused by: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.itsaky.androidide/com.itsaky.androidide.EditorActivity}: java.lang.NullPointerException
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3921)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4078)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2423)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:233)
	at android.os.Looper.loop(Looper.java:334)
	at android.app.ActivityThread.main(ActivityThread.java:8333)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:582)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1065)

**Comment by itsaky** [comment] 2022-07-01 07:21
Duplicate of #235.

**Closed by itsaky** 2022-07-01 07:21 UTC
