### ISSUE TITLE
the first window in just loading and loading.  

### ISSUE THREAD

**Issue by coderminhaj** [itsaky/AndroidIDE#354] opened 2022-08-09 18:02 UTC
i dont know what to do ? tried with old version but facing same problem.  my mobile's android version is 11

![Screenshot_20220809-235909870](https://user-images.githubusercontent.com/110194259/183726184-f85b2f65-0e05-4974-a1c6-00b052e6b10e.jpg)
![Screenshot_20220810-000014277](https://user-images.githubusercontent.com/110194259/183726324-be90c834-62d5-45d6-ae34-461414d3a877.jpg)

**Comment by itsaky** [comment] 2022-08-09 18:06
This is a duplicate of #224.

**Closed by itsaky** 2022-08-09 18:06 UTC
