### ISSUE TITLE
annoying Logsender

### ISSUE THREAD

**Issue by frrrrrits** [itsaky/AndroidIDE#24] opened 2021-11-19 21:03 UTC
im using two module and `com.itsaky.androidide.logsender.LogeSender`
its compiled in that two module.

i suggested to add a feature that give user options, to use logesender or not.

> What went wrong:
Execution failed for task ':app:mergeLibDexDebug'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.DexMergingTaskDelegate
> There was a failure while executing work items
> A failure occurred while executing com.android.build.gradle.internal.tasks.DexMergingWorkAction
> com.android.builder.dexing.DexArchiveMergerException: Error while merging dex archives:
Learn how to resolve the issue at https://developer.android.com/studio/build/dependencies#duplicate_classes.
Type com.itsaky.androidide.logsender.LogSender$Callback is defined multiple times: /storage/emulated/0/AndroidIDEProjects/app_name/library_one/build/.transforms/a3f5f5cd3e4e000b4145f4d283e66ebf/transformed/classes/classes.dex, /storage/emulated/0/AndroidIDEProjects/app_name/library_two/build/.transforms/187c6fa16d5942500a83d815c6ed2829/transformed/classes/classes.dex

**Comment by itsaky** [comment] 2021-11-20 01:22
I'm sorry for the inconvenience.

However, this is a duplicate of #17.

**Closed** 2021-11-20 01:22 UTC
Labels: duplicate
