### ISSUE TITLE
AndroidIDE crash

### ISSUE THREAD

**Issue by Gh0sts666** [itsaky/AndroidIDE#360] opened 2022-08-10 13:56 UTC
AndroidIDE crash report
Manufacturer: samsung
Device: SM-A107F
App version: 2.1.1-beta (211)

 Stacktrace: 
java.lang.IllegalStateException: Tooling API server has not been started
	at com.itsaky.androidide.services.GradleBuildService.checkServerStarted(GradleBuildService.java:358)
	at com.itsaky.androidide.services.GradleBuildService.initializeProject(GradleBuildService.java:292)
	at com.itsaky.androidide.EditorActivity.initializeProject(EditorActivity.java:911)
	at com.itsaky.androidide.actions.build.ProjectSyncAction.execAction(ProjectSyncAction.kt:44)
	at com.itsaky.androidide.actions.internal.DefaultActionsRegistry.addActionToMenu$lambda-1$lambda-0(DefaultActionsRegistry.kt:136)
	at com.itsaky.androidide.actions.internal.DefaultActionsRegistry.$r8$lambda$x3ssCnNYbdbBmuWXXzMq_mom94U(Unknown Source:0)
	at com.itsaky.androidide.actions.internal.DefaultActionsRegistry$$ExternalSyntheticLambda1.run(Unknown Source:6)
	at com.blankj.utilcode.util.ThreadUtils.runOnUiThread(ThreadUtils.java:70)
	at com.itsaky.androidide.actions.internal.DefaultActionsRegistry.addActionToMenu$lambda-1(DefaultActionsRegistry.kt:135)
	at com.itsaky.androidide.actions.internal.DefaultActionsRegistry.$r8$lambda$4QU30ZUG4MYnuZmK2rBaEKzRdQM(Unknown Source:0)
	at com.itsaky.androidide.actions.internal.DefaultActionsRegistry$$ExternalSyntheticLambda0.onMenuItemClick(Unknown Source:6)
	at androidx.appcompat.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:154)
	at androidx.appcompat.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:985)
	at androidx.appcompat.view.menu.MenuPopup.onItemClick(MenuPopup.java:128)
	at android.widget.AdapterView.performItemClick(AdapterView.java:376)
	at android.widget.AbsListView.performItemClick(AbsListView.java:1295)
	at android.widget.AbsListView$PerformClick.run(AbsListView.java:3539)
	at android.widget.AbsListView$3.run(AbsListView.java:4642)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:246)
	at android.app.ActivityThread.main(ActivityThread.java:8653)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)

**Comment by itsaky** [comment] 2022-08-10 13:58
Duplicate of #251.

**Closed by itsaky** 2022-08-10 13:58 UTC
