### ISSUE TITLE
Crash when "searching in project"

### ISSUE THREAD

**Issue by PgmDz** [itsaky/AndroidIDE#319] opened 2022-07-17 13:02 UTC
When clicking on search in the project presents this problem 

My device is a Moto e6s
Android 9.0

java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.widget.CheckBox.isChecked()' on a null object reference
	at com.itsaky.androidide.EditorActivity.lambda$createFindInProjectDialog$48$com-itsaky-androidide-EditorActivity(EditorActivity.java:1752)
	at com.itsaky.androidide.EditorActivity$$ExternalSyntheticLambda11.onClick(Unknown Source:6)
	at androidx.appcompat.app.AlertController$ButtonHandler.handleMessage(AlertController.java:167)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:6704)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:916)

**Comment by itsaky** [comment] 2022-07-17 13:04
Duplicate of #276.

**Closed by itsaky** 2022-07-17 13:04 UTC
