### ISSUE TITLE
[Bug]: App crashed

### ISSUE THREAD

**Issue by freethemesvk** [itsaky/AndroidIDE#409] opened 2022-08-25 10:13 UTC
### What happened?

AndroidIDE crash report
Manufacturer: xiaomi
Device: Redmi9
App version: 2.1.1-beta (211)

 Stacktrace: 
java.lang.NullPointerException
	at java.util.Objects.requireNonNull(Objects.java:220)
	at com.itsaky.androidide.EditorActivity.initializeLanguageServers(EditorActivity.java:1618)
	at com.itsaky.androidide.EditorActivity.startServices(EditorActivity.java:1605)
	at com.itsaky.androidide.EditorActivity.onCreate(EditorActivity.java:1129)
	at android.app.Activity.performCreate(Activity.java:7994)
	at android.app.Activity.performCreate(Activity.java:7978)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1309)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3404)
 Caused by: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.itsaky.androidide/com.itsaky.androidide.EditorActivity}: java.lang.NullPointerException
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3431)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3595)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:223)
	at android.app.ActivityThread.main(ActivityThread.java:7664)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)

### What's the expected behavior?

AndroidIDE crash report
Manufacturer: xiaomi
Device: Redmi9
App version: 2.1.1-beta (211)

 Stacktrace: 
java.lang.NullPointerException
	at java.util.Objects.requireNonNull(Objects.java:220)
	at com.itsaky.androidide.EditorActivity.initializeLanguageServers(EditorActivity.java:1618)
	at com.itsaky.androidide.EditorActivity.startServices(EditorActivity.java:1605)
	at com.itsaky.androidide.EditorActivity.onCreate(EditorActivity.java:1129)
	at android.app.Activity.performCreate(Activity.java:7994)
	at android.app.Activity.performCreate(Activity.java:7978)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1309)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3404)
 Caused by: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.itsaky.androidide/com.itsaky.androidide.EditorActivity}: java.lang.NullPointerException
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3431)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3595)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:223)
	at android.app.ActivityThread.main(ActivityThread.java:7664)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)

### What version of AndroidIDE you're using?

v2.1.1

### Relevant log output

```shell
AndroidIDE crash report
Manufacturer: xiaomi
Device: Redmi9
App version: 2.1.1-beta (211)

 Stacktrace: 
java.lang.NullPointerException
	at java.util.Objects.requireNonNull(Objects.java:220)
	at com.itsaky.androidide.EditorActivity.initializeLanguageServers(EditorActivity.java:1618)
	at com.itsaky.androidide.EditorActivity.startServices(EditorActivity.java:1605)
	at com.itsaky.androidide.EditorActivity.onCreate(EditorActivity.java:1129)
	at android.app.Activity.performCreate(Activity.java:7994)
	at android.app.Activity.performCreate(Activity.java:7978)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1309)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3404)
 Caused by: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.itsaky.androidide/com.itsaky.androidide.EditorActivity}: java.lang.NullPointerException
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3431)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3595)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:223)
	at android.app.ActivityThread.main(ActivityThread.java:7664)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
```

### Duplicate issues

- [ ] This issue has not been reported yet.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by itsaky** [comment] 2022-08-25 15:39
Duplicate of #235.

**Closed** 2022-08-25 15:40 UTC
Labels: bug
