### ISSUE TITLE
NPE in CachedIndexer.afterInsert

### ISSUE THREAD

**Issue by TimScriptov** [itsaky/AndroidIDE#265] opened 2022-07-06 18:03 UTC
```
AndroidIDE crash report
Manufacturer: Xiaomi
Device: M2102J20SG
App version: 2.1.2-beta (212)

 Stacktrace: 
java.lang.NullPointerException: Attempt to read from field 'int io.github.rosemoe.sora.text.CharPosition.line' on a null object reference
	at io.github.rosemoe.sora.text.CachedIndexer.afterInsert(CachedIndexer.java:419)
	at io.github.rosemoe.sora.text.Content.dispatchAfterInsert(Content.java:856)
	at io.github.rosemoe.sora.text.Content.insertInternal(Content.java:372)
	at io.github.rosemoe.sora.text.Content.insert(Content.java:331)
	at io.github.rosemoe.sora.widget.CodeEditor.commitText(CodeEditor.java:1746)
	at io.github.rosemoe.sora.widget.EditorInputConnection.commitTextInternal(EditorInputConnection.java:262)
	at io.github.rosemoe.sora.widget.EditorInputConnection.commitText(EditorInputConnection.java:212)
	at com.android.internal.view.IInputConnectionWrapper.executeMessage(IInputConnectionWrapper.java:549)
	at com.android.internal.view.IInputConnectionWrapper$MyHandler.handleMessage(IInputConnectionWrapper.java:111)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:210)
	at android.os.Looper.loop(Looper.java:299)
	at android.app.ActivityThread.main(ActivityThread.java:8250)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:556)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1045)
```

**Comment by itsaky** [comment] 2022-08-18 14:12
Duplicate of #208.

**Closed by itsaky** 2022-08-18 14:12 UTC
Labels: bug
